insert into products (name, description, image, price, stock) values ('name2', 'desc2', 'image2', 11, 11);
insert into products (name, description, image, price, stock, brand, age_category, gender_category) values ('name', 'desc', 'image', 11, 11, 'brand', '5-7','Fete'); 

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('name', 'desc', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/p/a/papusa-evi-love-cu-bicicleta-si-casca-roz_1.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/y/l/yl30005_001w_papusa_snapstar_yuki_1_.jpg', 11, 11, 'brand', '5-7','Fete');


insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('Papusa Maia la joaca', 'Facem totul impreuna! Fa toate activitatile care te incanta impreuna cu Maia si descopera cat de vesela este viata cu micuta ta prietena! Iubeste-o si ai grija de ea hranind-o, invatand-o sa faca pipi si facandu-I baita.Apoi distreaza-te colorand desenele haioase cu creioanele cerate incluse si pastreaza-le in cutiute deosebite. Setul contine: 1x papusa bebelus, 1x cadita de baie, 5x recipiente pentru baita: biberon, olita, farfurioara compartimentata, furculita, lingurita, 10x foi de colorat, 4x cutiute de asamblat, 8x creioane cerate', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/i/n/int1059_001w_papusa_maia_la_joaca_3_.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/i/n/int1059_001w_papusa_maia_la_joaca_2_.jpg', 100, 20, 'Maia', '3-8','Fete');  

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('Papusa Fancy Nancy Clancy', 'Papusa Fancy Nancy Clancy este asemenea personajului celebru din serialul tv cu acelasi nume. Are o personalitate puternica, este nerabdatoare sa descopere experiente noi si ii plac toate lucrurile extravagante.Traieste o aventura extraordinara cu papusa ta Fancy Nancy! Foloseste punguta cu accesorii speciale din pachet si transforma tinuta papusii tale pentru sezonul de iarna! Papusa este articulata la umeri si solduri in asa fel incat sa ii poti misca mainile si picioarele. Pachetul contine: 1 x papusa cu tinuta, 1 x punguta cu accesorii decorative', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/7/7/77351_001w_papusa_fancy_nancy_clancy_25_cm_1_.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/7/7/77351_001w_papusa_fancy_nancy_clancy_25_cm_2_.jpg', 90, 11, 'Disney', '3-8','Fete'); 

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('Papusa Kruselings', 'Cinci fete curajoase au fost chemate de catre o inima rosie si stralucitoare, Marele Opal de Foc, pentru a infrunta cosmarurile copiilor din timpul noptii si pentru a raspandi vise frumoase. In povestea Kruselings-Gardienii viselor este vorba despre prietenie, comunicare, apropierea dintre oameni si munca in echipa. Fiecare dintre cele cinci fete, venite din parti diferite ale lumii are propria poveste si o putere speciala, care cu siguranta ii va incanta pe copii. Luna, Vera, Sofia, Joy si Chloe, impreuna cu prietenul lor, Michael, stiu ca, cu ajutorul puterilor unice pe care le au, se pot confrunta cu orice provocare.', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/0/1/0126846_001_papusa_kruselings_chloe_pictorita_talentata_1_.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/0/1/0126846_001_papusa_kruselings_chloe_pictorita_talentata_2_.jpg', 130, 0, 'Kruselings', '5-8','Fete');  

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('Masinuta Maisto MotoSounds Lamborghini', 'Maisto Lamborghini Aventador are carcasa din material plastic. Este replicata scalata 1:24 a modelului de masina original. Caracteristici produs: design detaliat interior-exterior, realizata din material plastic, accesorii din material plastic,roti din cauciuc, efecte luminoase si sonore, functioneaza cu 2 baterii de tip AA', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/m/a/masinuta-maisto-motosounds-lamborghini-aventador-124.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/m/a/masinuta-maisto-motosounds-lamborghini-aventador-124_1.jpg', 55, 18, 'Maisto', '7-12+','Baieti'); 

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('Motocicleta cu telecomanda', 'Fanii sportului cu motor vor iubi aceasta motocicleta cu telecomanda de la Maisto. Licentiat oficial de Maisto, motocicleta Cyklone Drift are o proiectare unica a rotilor ce permite acesteia sa efectueze cascadorii incredibile si foarte usor de realizat. Banda de rulare a fiecarei roti de pe motocicleta Drift Cyklone este alcatuita din zeci de roti mai mici, care ii permit sa efectueze rotiri, drifturi laterale si alunecari diagonale cu o usurinta uimitoare. Caracteristici: roti proiectate special pentru drifturi, lumini Led, dimensiune aprox 22 cm, telecomanda (distanta pana la 35 m), frecventa 2,4 GHz, functie de rasucire 360 si drifturi, 40 de mini-roti', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/m/a/mais-82293_motocicleta_cu_telecomanda_maisto_cyklone_drifter_2_.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/m/a/mais-82293_motocicleta_cu_telecomanda_maisto_cyklone_drifter_1_.jpg', 250, 18, 'Maisto', '5-12+','Baieti');

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('Elicopter cu lumini', 'O colectie de vehicule pentru cei care nu se multumesc sa viseze la aventura, ci se avanta in plina distractie! Aceasta colectie te transforma intr-un adevarat pilot, pentru ca include elicoptere cu telecomanda, masinute cu elice care strabat orice teren si multe altele! Cool Machines Adventure te provoaca la actiune si la performanta! Caracteristici: 1x elicopter, lumini si sunet', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/i/n/int1356_001w_elicopter_cu_lumini_si_sunete_cool_machines_albastru_2_.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/i/n/int1356_001w_elicopter_cu_lumini_si_sunete_cool_machines_albastru_1_.jpg', 44, 38, 'Cool Machines', '4-8','Baieti');  

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('LEGO Salvarea alpacai', 'In jungla se aude un vuiet...un vulcan gata sa erupa, iar alpacalele sunt izolate pe versanti! Ajut-o pe Stephanie sa vina in ajutor in grozava ei canoe lunga din bustean. Elicopterul Miei este gata sa ridice animalele si sa le duca la adapost. Cand eruptia s-a terminat, du alpacalele inapoi la locul lor si exploreaza pesterile misterioase ale muntelui. Descopera pietrele pretioase si ia-le la tabara de baza pentru a le studia.', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/l/g/lg41432_001w_lego_friends_-_salvarea_alpacai_41432_.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/l/g/lg41432_001w_lego_friends_-_salvarea_alpacai_41433_.jpg', 300, 40, 'Lego', '7-8+','Fete');  

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('LEGO Creator Expert', 'Recreeaza una dintre minunile arhitecturale ale lumii cu acest set Taj Mahal LEGO® Creator Expert. Lansat pentru prima oara in 2008, aceasta uimitoare interpretare LEGO a unei constructii considerate de multi ca simbolul emblematic al iubirii, a fost relansata pentru a marca cea de-a 10-a aniversare. Cu peste 5.900 de piese LEGO, modelul surprinde maretia giganticului mausoleu de marmura alb-galbuie, si evidentiaza fatadele elaborate ale constructiei cu arcade largi, balcoane, ferestre cu arcade si detalii complexe. Ornamentele decorative din varful domului central, incaperile secundare boltite, minaretele avantate si o platforma ridicata ornamentala brazdata de arcade retrase si placi de ceramica detaliate in jurul bazei desavarsesc acest model splendid.', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/l/g/lg10256_001w_lego_creator_expert_-_taj_mahal_10256_.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/l/g/lg10256_001w_lego_creator_expert_-_taj_mahal_10258_.jpg', 700, 20, 'Lego', '8-12+','Fete, Baieti');  

insert into products (name, description, image_list, image_detail, price, stock, brand, age_category, gender_category) values ('Puzzle cu ceas', 'Creeaza in joaca un ceas de perete numai al tau!Cu cadran circular de asamblat cu diametrul de 33 cm, format din 100 de piese de puzzle, si cu mecanism de ceas functional! Continut: 1 ceas cu piulita, saiba si trei ace (orar, minutar, secundar), 100 de piese de puzzle, 1 cadran autoadeziv de asamblat din 2 piese, 1 piesa distantier autoadeziva', 'https://noriel.ro/media/catalog/product/cache/76c09b5e5e69aadae3d59418cb5d4562/i/n/int3206_001w_puzzle_cu_ceas_dinozauri_noriel_ora_de_joaca_1_.jpg','https://noriel.ro/media/catalog/product/cache/c682e6120e627a95f4ce21a5b384118b/i/n/int3176_001w_puzzle_cu_ceas_animale_noriel_ora_de_joaca_1_.jpg', 40, 21, 'Noriel', '5-10+','Fete, Baieti');  